CREATE TABLE CLIENT (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100)
);

CREATE TABLE PRODUCT(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    DESC_PRODUCT VARCHAR(100),
    PRICE_UNIT NUMERIC(20,2)
);

CREATE TABLE ORDERS(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    CLIENT_ID INTEGER REFERENCES CLIENT(ID),
    DATE_ORDER TIMESTAMP,
    TOTAL NUMERIC(20,2)
);

CREATE TABLE ITEM_ORDER(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    ORDERS_ID INTEGER REFERENCES ORDERS(ID),
    PRODUCT_ID INTEGER REFERENCES PRODUCT(ID),
    QUANTITY INTEGER
);

